In [49]:

import random
import numpy as np

### Rete Semplificata
###### 3 layers, 6 neuroni, 9 pesi e 4 biases
<img src="./img/rete_semplificata_3.svg" width="300px" />

In [48]:
class Network():

    def __init__(self, sizes):
        self.num_layers = len(sizes)
        
        self.sizes = sizes

        # self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.biases = []
        for y in sizes[1:]:
            self.biases.append(np.random.randn(y, 1))

        # per ogni layer (escluso il primo [:1])
        # appendo una matrice larga 1 e alta y
        # np.random.randn(y, 1) genera una matrice larga y e lunga x piena di numeri casuale generati secondo la ditribuzione gaussiana

        [
            [ # biases del 2° layer
                [-0.18229955], # bias del neurone c
                [ 0.55954105], # bias del neurone d
                [-0.1041088 ]  # bias del neurone e
            ],
            [ # bias del 3° layer
                [-0.29721879] # bias del neurone f
            ]
        ]



        # self.weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]
        self.weights = []
        for x, y in zip(sizes[:-1], sizes[1:]): # sizes[:-1] numero di layer indice i, sizes[:-1] numero di layer indice i + 1
            self.weights.append(np.random.randn(y, x))

        # print(list(zip(sizes[:-1], sizes[1:])))

        [
            [ # secondo layer di neuroni
                [-0.0696123 , -1.18933377], # pesi collegati al 1° dei 3 neuroni presenti nel 2° layer (rossi)
                [-0.04974523,  0.9851919 ], # pesi collegati al 2° dei 3 neuroni presenti nel 2° layer (verdi)
                [ 1.34270952,  0.93067125]  # pesi collegati al 3° dei 3 neuroni presenti nel 2° layer (blu)
            ], 
            [ # terzo layer di neuroni
                [-0.22923997,  1.76679014,  1.11225243] # pesi collegati all'unico neurone presente nel 3° layer (gialli)
            ]
        ]

    def feedforward(self, a):
        """ return the output of the network if "a" is input """

        # print("self.biases")
        # print(self.biases)
        # print("\nself.weights")
        # print(self.weights)

        # print("\nlist(zip(self.biases, self.weights))")
        # print(list(zip(self.biases, self.weights)))

        [
            ( # layer 2
                [ # biases dei 3 neuroni del layer 2
                    [ 0.20510307],
                    [-0.91035791],
                    [-0.02419269]
                ],
        
                [ # weights dei 3 neuroni del layer 2
                    [ 1.62232805,  1.19166118], # rossi
                    [-2.64924593,  0.36606946], # verdi
                    [ 1.33485666,  0.47252189]  # blu
                ]
            ), 
       
            ( #layer 3
                [ # bias del neurone del layer 3
                    [0.11012774]
                ],
             
                [ # weights del neurone del layer 3
                    [-0.4695252 , -1.41941377,  0.77848783] # gialli
                ]
            )
        ]

        for b, w in zip(self.biases, self.weights): # per ogni layer

            # esempio del primo layer
            print("\nw")
            print(w)

            # weight
            # [
            #   [ a  b ] 
            #   [ c  d ]
            #   [ e  f ]
            #  ]

            print("\na")
            print(a)

            # input
            # [x, y]

            print("\nnp.dot(w, a)")
            print(np.dot(w, a))

            # np.dot(w, a)
            # [ a*x + b*y, c*x + d*y, e*x + f*y ]

            print("\nb")
            print(b)

            # biases
            # [ b1, b2, b3 ]

            print("\nnp.dot(w, a)+b")
            print(np.dot(w, a)+b)

            # np.dot(w, a) + b
            # [ a*x + b*y + b1,
            #   c*x + d*y + b2,
            #   e*x + f*y + b3 ]

            print("\nsigmoid(np.dot(w, a)+b)")
            print(self.sigmoid(np.dot(w, a)+b))
            
            a = self.sigmoid(np.dot(w, a)+b)


        return a

    def SGD(self, training_data, epochs, mini_batch_size, eta, test_data=None):
        """ SGD: mini-batch Stochastic (random) Gradient Descent """

        if test_data: 
            n_test = len(test_data)

        n = len(training_data)

        for j in range(epochs):
            random.shuffle(training_data)

            mini_batches = [
                training_data[k:k+mini_batch_size]
                for k in range(0, n, mini_batch_size)]
            
            for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta)

            if test_data:
                print(f"Epoch {j}: {self.evaluate(test_data)} / {n_test}")
            else:
                print(f"Epoch {j} complete")

    
    def sigmoid(self, z):
        """ Sigmoid function """
        return 1.0/(1.0+np.exp(-z))
    
    def sigmoid_prime(self, z):
        """ Derivative of the sigmoid function """
        return self.sigmoid(z)*(1-self.sigmoid(z))

    def export(self): # da completare
        return list(zip(self.weights, self.biases))




net = Network([2, 3, 1])

net.feedforward([1, 2])

net.export()


w
[[ 0.12240879 -1.15445244]
 [ 0.64723907 -1.92025825]
 [-0.02849609  1.04300091]]

a
[1, 2]

np.dot(w, a)
[-2.18649609 -3.19327742  2.05750574]

b
[[-0.123468  ]
 [ 1.40118644]
 [-0.45109353]]

np.dot(w, a)+b
[[-2.3099641  -3.31674542  1.93403773]
 [-0.78530965 -1.79209097  3.45869218]
 [-2.63758963 -3.64437095  1.6064122 ]]

sigmoid(np.dot(w, a)+b)
[[0.09030109 0.03500117 0.87369566]
 [0.31317666 0.14281656 0.96948931]
 [0.06675805 0.02547206 0.83291267]]

w
[[-0.14258062 -1.47871857 -0.51700579]]

a
[[0.09030109 0.03500117 0.87369566]
 [0.31317666 0.14281656 0.96948931]
 [0.06675805 0.02547206 0.83291267]]

np.dot(w, a)
[[-0.51048963 -0.22934518 -1.98879458]]

b
[[0.10083143]]

np.dot(w, a)+b
[[-0.4096582  -0.12851375 -1.88796315]]

sigmoid(np.dot(w, a)+b)
[[0.39899408 0.46791571 0.13147688]]


[(array([[ 0.12240879, -1.15445244],
         [ 0.64723907, -1.92025825],
         [-0.02849609,  1.04300091]]),
  array([[-0.123468  ],
         [ 1.40118644],
         [-0.45109353]])),
 (array([[-0.14258062, -1.47871857, -0.51700579]]), array([[0.10083143]]))]